// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
/// 

    
class DefaultFirebaseOptions {

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkw5uAllajodPFk9Je4lPjx2a9HXOMS_8',
    appId: '1:1005934299751:web:b5c4b0d675fdd2afd162c2',
    messagingSenderId: '1005934299751',
    projectId: 'guerbaapp',
    authDomain: 'guerbaapp.firebaseapp.com',
    storageBucket: 'guerbaapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQABgP1-1fQAgvwWzEOhsI8NyK9qi_5f0',
    appId: '1:1005934299751:android:21de20169475bf90d162c2',
    messagingSenderId: '1005934299751',
    projectId: 'guerbaapp',
    storageBucket: 'guerbaapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI3mkt0CcyVRqyGivHpSKrhvL23W3zbRU',
    appId: '1:1005934299751:ios:2d2139b894704addd162c2',
    messagingSenderId: '1005934299751',
    projectId: 'guerbaapp',
    storageBucket: 'guerbaapp.appspot.com',
    iosBundleId: 'com.example.guerbaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI3mkt0CcyVRqyGivHpSKrhvL23W3zbRU',
    appId: '1:1005934299751:ios:2d2139b894704addd162c2',
    messagingSenderId: '1005934299751',
    projectId: 'guerbaapp',
    storageBucket: 'guerbaapp.appspot.com',
    iosBundleId: 'com.example.guerbaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkw5uAllajodPFk9Je4lPjx2a9HXOMS_8',
    appId: '1:1005934299751:web:0c21edc5b5325a9bd162c2',
    messagingSenderId: '1005934299751',
    projectId: 'guerbaapp',
    authDomain: 'guerbaapp.firebaseapp.com',
    storageBucket: 'guerbaapp.appspot.com',
  );
}
